package it.aranciaict.jobmatch.domain.enumeration;

/**
 * The CompanySectorType enumeration.
 */
public enum CompanySectorType {
	AEROSPACE, DEFENSE_CONTRACTORS, AGRIBUSINESS, AGRICULTURAL_SERVICES_PRODUCTS, AGRICULTURE, AIR_TRANSPORT, AIRLINES,
	ALCOHOLIC_BEVERAGES, ENERGY, ARCHITECTURAL_SERVICES, LAW, AUTO_DEALERS, AUTO_MANUFACTURERS, AUTOMOTIVE, BANKING,
	COMMERCIAL, BARS_RESTAURANTS, BOOKS_MAGAZINES_NEWSPAPERS, BROADCASTERS, RADIO_TV, BUILDERS_GENERAL_CONTRACTORS,
	BUILDERS_RESIDENTIAL, BUILDING_MATERIALS_EQUIPMENT, BUILDING_TRADE_UNIONS, ICT_IT, SERVICES, OTHERS
}
