import { Moment } from 'moment';
import { ISkillTag } from './skill-tag.model';
import { ISkill } from './skill.model';
import { IJobExperience } from './job-experience.model';

export const enum GenderType {
    MALE = 'MALE',
    FEMALE = 'FEMALE'
}

export enum Country {
    IT = 'IT',
    AF = 'AF',
    AL = 'AL',
    DZ = 'DZ',
    AD = 'AD',
    AO = 'AO',
    AI = 'AI',
    AQ = 'AQ',
    AG = 'AG',
    AN = 'AN',
    SA = 'SA',
    AR = 'AR',
    AM = 'AM',
    AW = 'AW',
    AU = 'AU',
    AT = 'AT',
    AZ = 'AZ',
    BS = 'BS',
    BH = 'BH',
    BD = 'BD',
    BB = 'BB',
    BE = 'BE',
    BZ = 'BZ',
    BJ = 'BJ',
    BM = 'BM',
    BT = 'BT',
    BY = 'BY',
    BO = 'BO',
    BA = 'BA',
    BW = 'BW',
    BR = 'BR',
    BN = 'BN',
    BG = 'BG',
    BF = 'BF',
    BI = 'BI',
    KH = 'KH',
    CM = 'CM',
    CA = 'CA',
    CV = 'CV',
    TD = 'TD',
    CL = 'CL',
    CN = 'CN',
    CY = 'CY',
    CO = 'CO',
    CG = 'CG',
    KR = 'KR',
    KP = 'KP',
    CR = 'CR',
    CI = 'CI',
    HR = 'HR',
    CU = 'CU',
    DK = 'DK',
    DM = 'DM',
    EC = 'EC',
    EG = 'EG',
    SV = 'SV',
    AE = 'AE',
    ER = 'ER',
    EE = 'EE',
    ET = 'ET',
    RU = 'RU',
    FJ = 'FJ',
    PH = 'PH',
    FI = 'FI',
    FR = 'FR',
    GA = 'GA',
    GM = 'GM',
    GE = 'GE',
    GS = 'GS',
    DE = 'DE',
    GH = 'GH',
    JM = 'JM',
    JP = 'JP',
    GI = 'GI',
    DJ = 'DJ',
    JO = 'JO',
    GR = 'GR',
    GD = 'GD',
    GL = 'GL',
    GP = 'GP',
    GU = 'GU',
    GT = 'GT',
    GG = 'GG',
    GN = 'GN',
    GQ = 'GQ',
    GW = 'GW',
    GY = 'GY',
    GF = 'GF',
    HT = 'HT',
    HM = 'HM',
    HN = 'HN',
    HK = 'HK',
    IN = 'IN',
    ID = 'ID',
    IR = 'IR',
    IQ = 'IQ',
    IE = 'IE',
    IS = 'IS',
    BV = 'BV',
    CX = 'CX',
    NF = 'NF',
    IM = 'IM',
    AX = 'AX',
    KY = 'KY',
    CC = 'CC',
    KM = 'KM',
    CK = 'CK',
    FK = 'FK',
    FO = 'FO',
    PN = 'PN',
    SB = 'SB',
    TC = 'TC',
    VI = 'VI',
    VG = 'VG',
    IL = 'IL',
    JE = 'JE',
    KZ = 'KZ',
    KE = 'KE',
    KG = 'KG',
    KI = 'KI',
    KO = 'KO',
    KW = 'KW',
    LA = 'LA',
    LS = 'LS',
    LV = 'LV',
    LB = 'LB',
    LR = 'LR',
    LY = 'LY',
    LI = 'LI',
    LT = 'LT',
    LU = 'LU',
    MO = 'MO',
    MK = 'MK',
    MG = 'MG',
    MW = 'MW',
    MY = 'MY',
    MV = 'MV',
    ML = 'ML',
    MT = 'MT',
    MP = 'MP',
    MA = 'MA',
    MH = 'MH',
    MQ = 'MQ',
    MR = 'MR',
    MU = 'MU',
    YT = 'YT',
    MX = 'MX',
    MD = 'MD',
    MC = 'MC',
    MN = 'MN',
    ME = 'ME',
    MS = 'MS',
    MZ = 'MZ',
    MM = 'MM',
    NA = 'NA',
    NR = 'NR',
    NP = 'NP',
    NI = 'NI',
    NE = 'NE',
    NG = 'NG',
    NU = 'NU',
    NO = 'NO',
    NC = 'NC',
    NZ = 'NZ',
    OM = 'OM',
    NL = 'NL',
    CB = 'CB',
    PK = 'PK',
    PW = 'PW',
    PA = 'PA',
    PG = 'PG',
    PY = 'PY',
    PE = 'PE',
    PF = 'PF',
    PL = 'PL',
    PT = 'PT',
    PR = 'PR',
    QA = 'QA',
    GB = 'GB',
    CZ = 'CZ',
    CF = 'CF',
    DO = 'DO',
    CD = 'CD',
    SK = 'SK',
    RE = 'RE',
    RO = 'RO',
    RW = 'RW',
    EH = 'EH',
    KN = 'KN',
    LC = 'LC',
    PM = 'PM',
    VC = 'VC',
    WS = 'WS',
    AS = 'AS',
    SM = 'SM',
    SH = 'SH',
    SN = 'SN',
    RS = 'RS',
    CS = 'CS',
    SC = 'SC',
    SL = 'SL',
    SG = 'SG',
    SY = 'SY',
    SI = 'SI',
    SO = 'SO',
    ES = 'ES',
    LK = 'LK',
    US = 'US',
    FM = 'FM',
    VA = 'VA',
    ZA = 'ZA',
    SD = 'SD',
    SS = 'SS',
    SR = 'SR',
    SJ = 'SJ',
    SE = 'SE',
    CH = 'CH',
    SZ = 'SZ',
    ST = 'ST',
    TJ = 'TJ',
    TW = 'TW',
    TZ = 'TZ',
    TF = 'TF',
    IO = 'IO',
    PS = 'PS',
    TH = 'TH',
    TL = 'TL',
    TG = 'TG',
    TK = 'TK',
    TO = 'TO',
    TT = 'TT',
    TN = 'TN',
    TR = 'TR',
    TM = 'TM',
    TV = 'TV',
    UA = 'UA',
    UG = 'UG',
    HU = 'HU',
    UY = 'UY',
    UZ = 'UZ',
    VU = 'VU',
    VE = 'VE',
    VN = 'VN',
    WF = 'WF',
    YE = 'YE',
    ZM = 'ZM',
    ZW = 'ZW',
    OO = 'OO'
}

export interface ICandidate {
    id?: number;
    createdBy?: string;
    lastModifiedBy?: string;
    createdDate?: Moment;
    lastModifiedDate?: Moment;
    lastName?: string;
    firstName?: string;
    gender?: GenderType;
    birthday?: Moment;
    streetAddress?: string;
    email?: string;
    phone?: string;
    mobilePhone?: string;
    country?: Country;
    region?: string;
    province?: string;
    city?: string;
    cap?: string;
    note?: any;
    noteEN?: any;
    enabled?: boolean;
    userId?: number;
    userName?: string;
    imageUrl?: string;
    editAvailable?: boolean;
    deleteAvailable?: boolean;
}

export class Candidate implements ICandidate {
    constructor(
        public id?: number,
        public createdBy?: string,
        public lastModifiedBy?: string,
        public createdDate?: Moment,
        public lastModifiedDate?: Moment,
        public lastName?: string,
        public firstName?: string,
        public gender?: GenderType,
        public birthday?: Moment,
        public streetAddress?: string,
        public email?: string,
        public phone?: string,
        public mobilePhone?: string,
        public country?: Country,
        public region?: string,
        public province?: string,
        public city?: string,
        public cap?: string,
        public note?: any,
        public noteEN?: any,
        public enabled?: boolean,
        public userId?: number,
        public userName?: string,
        public imageUrl?: string,
        public editAvailable?: boolean,
        public deleteAvailable?: boolean
    ) {
        this.enabled = this.enabled || false;
        this.editAvailable = this.editAvailable || false;
        this.deleteAvailable = this.deleteAvailable || false;
    }
}

export class SelectableCandidate implements ICandidate {
    constructor(
        public id?: number,
        public createdBy?: string,
        public lastModifiedBy?: string,
        public createdDate?: Moment,
        public lastModifiedDate?: Moment,
        public lastName?: string,
        public firstName?: string,
        public gender?: GenderType,
        public birthday?: Moment,
        public streetAddress?: string,
        public email?: string,
        public phone?: string,
        public mobilePhone?: string,
        public country?: Country,
        public region?: string,
        public province?: string,
        public city?: string,
        public cap?: string,
        public note?: any,
        public noteEN?: any,
        public enabled?: boolean,
        public userId?: number,
        public userName?: string,
        public imageUrl?: string,
        public editAvailable?: boolean,
        public deleteAvailable?: boolean,
        public selected?: boolean
    ) {
        this.enabled = this.enabled || false;
        this.editAvailable = this.editAvailable || false;
        this.deleteAvailable = this.deleteAvailable || false;
        this.selected = this.selected || false;
    }
}

export class CandidateItem implements ICandidate {
    constructor(
        public id?: number,
        public createdBy?: string,
        public lastModifiedBy?: string,
        public createdDate?: Moment,
        public lastModifiedDate?: Moment,
        public lastName?: string,
        public firstName?: string,
        public gender?: GenderType,
        public birthday?: Moment,
        public streetAddress?: string,
        public email?: string,
        public phone?: string,
        public mobilePhone?: string,
        public country?: Country,
        public region?: string,
        public province?: string,
        public city?: string,
        public cap?: string,
        public note?: any,
        public noteEN?: any,
        public enabled?: boolean,
        public userId?: number,
        public userName?: string,
        public imageUrl?: string,
        public editAvailable?: boolean,
        public deleteAvailable?: boolean,
        public skills?: ISkill[],
        public currentJobExperience?: IJobExperience
    ) {
        this.enabled = this.enabled || false;
        this.editAvailable = this.editAvailable || false;
        this.deleteAvailable = this.deleteAvailable || false;
    }
}

export class SearchCandidate {
    constructor(
        public firstName?: string,
        public lastName?: string,
        public country?: Country,
        public skillsTag?: ISkillTag[],
        public skillTagName?: string,
        public currentJobTitle?: string,
        public currentJobCountry?: string,
        public currentJobCity?: string
    ) {
        this.skillsTag = [];
    }
}
