export const DATE_FORMAT = 'YYYY-MM-DD';
export const DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const MAX_SIZE_PROFILE_IMAGE = 2 * 1024 * 1024;
export const JOB_OFFERS_TO_PROMOTE_SESSION = 'JOB_OFFERS_TO_PROMOTE';
export const CANDIDATES_SELECTED_SESSION = 'CANDIDATES_SELECTED';
export const LAST_CANDIDATES_SELECTED_SESSION = 'LAST_CANDIDATES_SELECTED_SESSION';
